@startmindmap

*[#Pink] Referatsthemen
	*[#LightBlue] P1 Netzwerktechnologien
	*[#LightBlue] P2 Netzwerkdienste
	*[#LightBlue] P3 Netzwerkmanagement & Netzwerksicherheit
	*[#LightBlue] J4 Enterprise Architekturen
		*[#LightGreen] Testing (Balog Danijel)
			* Frontend
				*_ Selenium
					*_ Beispiel mit Selenium & Java
				*_ Graphene
			* Backend
				*_ JPA
					*_ JavaSE-JUnit Client, der Korrektheit eines Datenmodells prüft
				*_ REST loadtesting mit Galing
				*_ Cucumber
				*_ REST API testing mit Karate
				*_ RESTasured
				*_ Testcontainers
			* Theorie
		*[#LightGreen] CDI (Schwarz Markus)
			*_ Konzepte
				*_ @Inject vs. @EJB
				*_ Events
					*_ Synchronous
					*_ Asynchronous
				*_ Decorators
				*_ Interceptors
			*_ Implementierungen
				*_ ArC (Quarkus)
				*_ Seam
				*_ Weld
	*[#LightBlue] J5 Webapplikationen
	*[#LightBlue] J6 Client-Server Architekturen & Mobile Computing
	*[#LightBlue] J7 Systemnahe & hardwarenahe Programmierung

@endmindmap