@startuml

interface Reservierungen <<rest-interface>>

frame backend-server {
    component "quarkus-backend" <<component>> as backend
}

database "db-backend" as db {
}

backend --> db : uses

backend -- Reservierungen

frame webserver {
    component "frontend (angular)" <<component>> as frontend
}

frame customer {
    component browser <<component>>
    component [rest-client] <<subcomponent>>
}

Reservierungen )-- [rest-client]
browser ..> frontend : load
browser *-- [rest-client]
@enduml