@startuml oauth-flow

hnote over front : get app
"frontend-server" as front <- browser : GET js-app
browser <-- front : response
...

group js-app [client]
...

hnote over browser : get protected data
browser -> "backend-server" as back : GET protected data\n <b>without JWT!</b>
back --> browser : not allowed!
...

hnote over browser : get auth-code
browser -> auth : GET auth-code\n<i> + clientID\n<i> + response type\n<i> + scopes</i>\n<i> + redirection URL for later</i>

note over auth
auth-server evaluates if a login is required...
end note

else needs authentication
auth --> browser : authentication form
browser -> auth : form data

note over auth
auth-server evaluates authentication data
end note

else authenticated
auth --> browser : redirect to redirection URL\n <b>+ auth-code</b>
...

hnote over browser : get JWT
browser -> auth : token-request\n<i> + clientID\n<i> + client secret\n<b> + auth-code</b>

note over auth
verifies data
end note

auth --> browser : <b>access-token (JWT)</b>
...

hnote over browser : get protected data
browser -> back : GET protected data\n <b>+ JWT</b>
back --> browser : response with protected data

end

@enduml