@startuml

object customer {
    custNr
    firstName
    secondName
}

object borrowData {
    date
    daysUntilReturn
    price
}

object invoice {
    date
    price
}

object payment {
    date
    method
    price
}

book --o borrowData : n
customer --o borrowData : 1
invoice --* borrowData : 1
payment --* invoice : n

object book {
    ID
    ISBN
    title
    author
    genre
    priceForOneDay
}

@enduml