@startuml

object customer {
    firstName
    lastName
    birthday
    telephone
}

object yearlySubscription {
    year
}

object invoice {
    value
    isPayed
    paymentMethod
}

object lendout {
    date
    lendingDuration
}

yearlySubscription }o..|| customer
invoice ||..|{ yearlySubscription

lendout }o..|| customer
lendout |o..|{ book

object book {
    author
    publisher
    ISBN
    releaseDate
    language
    pricePerDay
    title
}

@enduml