@startuml

object customer {
    custNr
    firstName
    secondName
}

object borrowData {
    date
    daysUntilReturn
    price
}

object invoice {
    date
    price
}

object payment {
    date
    method
    price
}

book "m" -- "n" borrowData
customer "1" -- "n" borrowData
invoice "n" -- "1" borrowData
payment "n" -- "1" invoice

object book {
    ID
    ISBN
    title
    author
    genre
    priceForOneDay
}

@enduml